### ISSUE TITLE
User Button & Account Portal

### ISSUE THREAD

**Issue by feliche93** [stormynight9/clerk-shadcn-theme#1]
@stormynight9 awesome work on setting up the theme for sign in and sign up?

Would you also consider adding some themed variables for the User Account Button and the resulting modals?

Cheers, 

Felix

**Comment by stormynight9** [comment]
@feliche93 Glad the theme setup was helpful! I usually create components as needed and don't have plans for the rest. However I'm open for PR's.

**Comment by trulymittal** [comment]
@feliche93 If you create these components Account/UserButton please share them

**Comment by tomwatkins1994** [comment]
> @feliche93 If you create these components Account/UserButton please share them

I've been working on the user account and modal that it opens and I think I've got it mostly. I've submitted a PR #2 for these changes, regardless as to if it's merged or not, here is the CSS if you want to try it:

```css
.cl-formButtonPrimary {
    @apply inline-flex h-9 items-center justify-center whitespace-nowrap rounded-md bg-primary px-3 text-xs font-medium text-primary-foreground ring-offset-background transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50;
}

.cl-card,
.cl-socialButtonsBlockButton,
.cl-alert,
.cl-identityPreview,
.cl-phoneInputBox,
.cl-userButtonPopoverCard {
    @apply border border-input bg-background;
}

.cl-headerTitle,
.cl-socialButtonsBlockButtonText,
.cl-loading,
.cl-formFieldLabel,
.cl-formHeaderTitle,
.cl-selectButton__countryCode,
.cl-selectButton__countryCode p,
.cl-selectOption p,
.cl-selectOption div,
.cl-modalCloseButton,
.cl-navbarButton,
.cl-breadcrumbsItem.cl-breadcrumbsItem__currentPage,
.cl-profileSectionTitle p,
.cl-userPreviewTextContainer,
.cl-profileSectionContent p,
.cl-form p {
    @apply dark:text-foreground;
}

.cl-headerSubtitle,
.cl-dividerText,
.cl-footerActionText,
.cl-alertText,
.cl-formFieldInfoText,
.cl-formFieldSuccessText,
.cl-identityPreviewText,
.cl-userButtonPopoverActionButton,
.cl-userButtonPopoverActionButton svg,
.cl-userButtonPopoverActionButtonText,
.cl-userButtonPopoverFooter p,
.cl-userButtonPopoverFooter a,
.cl-formHeaderSubtitle,
.cl-breadcrumbsItem,
.cl-breadcrumbsItemDivider,
.cl-fileDropAreaHint,
.cl-fileDropAreaFooterHint,
.cl-form
    p[data-localization-key="userProfile.emailAddressPage.emailCode.formHint"] {
    @apply text-muted-foreground;
}

.cl-dividerLine {
    @apply bg-border;
}

.cl-formFieldInput[type="text"],
.cl-formFieldInput[type="email"],
.cl-formFieldInput[type="password"] {
    @apply flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-foreground ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50;
}

.cl-footerActionLink {
    @apply text-accent-foreground underline hover:text-accent-foreground/90;
}

.cl-otpCodeFieldInput {
    @apply border border-b-input text-foreground;
}

.cl-formResendCodeLink {
    @apply text-primary disabled:opacity-90;
}

.cl-selectSearchInput__countryCode {
    @apply flex h-10 w-full rounded-md border border-b border-input bg-background text-foreground ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50;
}

.cl-selectOptionsContainer__countryCode {
    @apply border border-input bg-background;
}

.cl-internal-icon {
    @apply text-foreground;
}

.cl-profileSectionTitle {
    @apply border-b border-input;
}

button[data-localization-key="userProfile.start.dangerSection.deleteAccountButton"] {
    @apply bg-destructive text-destructive-foreground hover:bg-destructive/90;
}

.cl-avatarImageActionsUpload,
.cl-fileDropAreaButtonPrimary,
.cl-formButtonReset,
.cl-accordionContent
    button[data-localization-key="userProfile.start.emailAddressesSection.detailsAction__unverified"] {
    @apply text-blue-600 dark:text-blue-400;
}

.cl-avatarImageActionsRemove,
.cl-accordionContent
    button[data-localization-key="userProfile.start.emailAddressesSection.destructiveAction"] {
    @apply text-destructive dark:text-red-400;
}

.cl-fileDropAreaBox {
    @apply bg-accent;
}

.cl-fileDropAreaIconBox {
    @apply dark:bg-slate-700;
}

/* Hover styling */

.cl-userButtonPopoverActionButton,
.cl-profileSectionPrimaryButton,
.cl-accordionTriggerButton,
.cl-navbarButton {
    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;
    @apply hover:bg-accent hover:text-accent-foreground;
}

/* Dark mode variable overrides */

.dark {
    .cl-badge {
        --bg: #bfdbfe;
        --accent: #1e3a8a;
    }
    .cl-badge[data-localization-key="badge__unverified"] {
        --bg: #fecaca;
        --accent: #991b1b;
    }
    .cl-userButtonPopoverActionButton,
    .cl-profileSectionPrimaryButton,
    .cl-accordionTriggerButton,
    .cl-navbarButton {
        --accent: 217.2 32.6% 17.5%;
        --accent-foreground: 210 40% 98%;
    }
}
```
